# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libv8-dev
      - libcurl4-openssl-dev
      - libxml2-dev

r:
- 3.2
- 3.3
- 3.4
- 3.5
- oldrel
- release
- devel

r_github_packages:
  - ColinFay/fryingpane
  - mrchypark/krlift
